;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        electric-newline-and-maybe-indent
        helm-M-x
        helm-show-kill-ring
        help-for-help
        ido-find-file
        kill-region
        ruby-electric-bar
        ruby-electric-closing-char
        ruby-electric-hash
        ruby-send-definition
        view-emacs-debugging
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        haml-electric-backspace
        helm-mini
        mouse-set-region
        rspec-toggle-spec-and-target
        rspec-verify-method
        ruby-electric-curlies
        ruby-electric-delete-backward-char
        ruby-electric-matching-char
        ruby-electric-space/return
        transpose-words
        view-order-manuals
        yas-expand
        ))
